import {ref} from "vue";

export const AVAILABLE_NOTES = ref([
    {
        id: 1,
        banner: 'Red',
        title: 'aespa!',
        group: 'K-Pop Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: true,
    },
    {
        id: 2,
        banner: 'Blue',
        title: 'I love myself',
        group: 'Personal Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: false,
    },
    {
        id: 3,
        banner: 'Green',
        title: 'DRAMA!',
        group: 'K-Pop Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: false,
    },
    {
        id: 4,
        banner: 'Orange',
        title: 'Algebra',
        group: 'School Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: true,
    },
    {
        id: 5,
        banner: 'Gray',
        title: 'aespaicy',
        group: 'K-Pop Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: true,
    },
    {
        id: 6,
        banner: 'Purple',
        title: 'Mathematics',
        group: 'School Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: false,
    },
    {
        id: 7,
        banner: 'Emerald',
        title: 'You and I',
        group: 'Personal Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: true,
    },
    {
        id: 8,
        banner: 'Pink',
        title: 'Me, Myself, and I',
        group: 'Personal Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: false,
    },
    {
        id: 9,
        banner: 'Cyan',
        title: 'Science is good.',
        group: 'School Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: true,
    },
    {
        id: 10,
        banner: 'Green',
        title: 'Katarina and Winter',
        group: 'K-Pop Stuff',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: true,
    },
    {
        id: 11,
        banner: 'Red',
        title: 'Items to buy.',
        group: 'Others',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: false,
    },
    {
        id: 12,
        banner: 'Purple',
        title: 'Meat or Beef?',
        group: 'Others',
        content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ultrices euismod neque, tempor egestas urna pretium a. Sed ut purus non nisl ornare imperdiet ut nec metus. Duis sollicitudin faucibus lacus, vel vehicula metus dapibus sit amet. Proin quis molestie nibh, vel volutpat leo. Aliquam viverra ipsum at fermentum dapibus.',
        date: '08/23/2023',
        favorite: false,
    },
])